### ISSUE TITLE
Papyrus - ProR Plugin does not work on Release 22 of OpenETCS toolchain

### ISSUE THREAD

**Issue by MatthieuPERIN** [openETCS/toolchain#464]
I have try with the win32_64 RCP found on the toolchain repository with basic test models.

I might have a look on that on January.

**Comment by MatthieuPERIN** [comment]
Tested, still not working on 2015-01-21.

I will try to have a deeper look.

**Comment by MatthieuPERIN** [comment]
Testing Done.

- [x] ProR (V11 from update site) tracing is working with a standard Kepler SR2 Eclipse with Papyrus & OpenETCS plugins in a runtime if you use WP3 models for ReqIf.

- [ ] ProR (V11 from update site) tracing plugin seems to fail on non WP3 ReqIf models due to the fact that I am not able to populate a ReqIf specification (numerous java errors) to make the tests.

- [ ] ProR (V10 ?!) tracing is __not working__ within R22 release of the toolchain (see below for the error trace).

I will try a build on the CEA Continous integration to see if V11 of ProR is the key.



_TRACE_

java.lang.NullPointerException
	at org.eclipse.rmf.reqif10.pror.editor.agilegrid.ProrLayoutAdvisor.getRowHeight(ProrLayoutAdvisor.java:96)
	at org.eclipse.rmf.reqif10.pror.editor.agilegrid.ProrAgileGridViewer$10.getLocation(ProrAgileGridViewer.java:821)
	at org.eclipse.emf.edit.ui.dnd.EditingDomainViewerDropAdapter.helper(EditingDomainViewerDropAdapter.java:284)
	at org.eclipse.emf.edit.ui.dnd.EditingDomainViewerDropAdapter.dragOver(EditingDomainViewerDropAdapter.java:191)
	at org.eclipse.rmf.reqif10.pror.editor.agilegrid.ProrAgileGridViewer$10.dragOver(ProrAgileGridViewer.java:800)
	at org.eclipse.swt.dnd.DNDListener.handleEvent(DNDListener.java:80)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.eclipse.swt.dnd.DropTarget.DragOver(DropTarget.java:366)
	at org.eclipse.swt.dnd.DropTarget.DragOver_64(DropTarget.java:340)
	at org.eclipse.swt.dnd.DropTarget$3.method4(DropTarget.java:252)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback4(COMObject.java:101)
	at org.eclipse.swt.internal.ole.win32.COM.DoDragDrop(Native Method)
	at org.eclipse.swt.dnd.DragSource.drag(DragSource.java:363)
	at org.eclipse.swt.dnd.DragSource.access$0(DragSource.java:289)
	at org.eclipse.swt.dnd.DragSource$1.handleEvent(DragSource.java:172)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:140)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:611)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

**Comment by MatthieuPERIN** [comment]
After a lot of work: pom cleaning and plugin moving and eclipse based configuration by-passed by using core maven functionality, the first alpha build of LUNA release is up.

Note that this first alpha version is __for test purpose__ and should note be used in production!

Please remember that __model opened in Luna cannot be used anymore in kepler__ due to the migration of UML element to a newer version.

Next steps are:
* [ ] add the test plugins
* [ ] add the RT Tester from University of Bremen
* [ ] test, test, test !

**Comment by MatthieuPERIN** [comment]
No bad returns from testers of Alpha 1 release, alpha two have tests and RT tester plugin included.

Closing.
